LocalResource.js
connect.js

Resolves [STCON-47:](https://issues.folio.org/browse/STCON-47) This addresses the fix to the init methods logic.
It does, however, introduce several regressions:
[UIU-314](https://issues.folio.org/browse/UIU-314)
[UIIT-80](https://issues.folio.org/browse/UIIT-80)
[UICHKOUT-32](https://issues.folio.org/browse/UICHKOUT-32)
[UICHKIN-8](https://issues.folio.org/browse/UICHKIN-8)
Several of these are serious regressions (UICHKIN-8 specifically) and we should decide how we want to proceed.

Fixed STCON-47: init is checking for prexisting store data

---

RESTResource/RESTResource.js

Thanks to Zak for spotting this!

Log object, not stringification

---

CHANGELOG.md
RESTResource/RESTResource.js

verbOptions returns null if the templated values are incomplete

---

RESTResource/RESTResource.js

Will facilitate work on STCON-59 if we ever come back to that.

Add logging, in category 'connect-dup', of duplicate-request detection

---

CHANGELOG.md
RESTResource/RESTResource.js
RESTResource/actionCreatorsFor.js
RESTResource/reducer.js
package.json

Fixes STCON-64
Available from v3.1.1.

Failed fetches on a resource clear existing data from that resource

---

babel-test-hook.js
connect.js
package.json
test/integration.js

After upgrading react-tether, the new context API works.

use new context API

---

CHANGELOG.md

Proper heading for v3.2.0 change-log entry

---

connect.js

Related to [UIEH-570](https://issues.folio.org/browse/UIEH-570) and folio-org/stripes-core#490
Not unsubscribing from the redux store can cause memory leaks. The leak found here in `stripes-connect` wasn't too substantial, but should still be fixed.
Unsubscribe from the store in a connected component's `componentWillUnmount` hook.
- For more info about this leak, [check out the `stripes-core` PR](https://github.com/folio-org/stripes-core/pull/490)

Unsubscribe from store on unmount

---

package.json

A patch version of lodash should be a nonissue and the new mocha still works for this test suite.

Updates STRIPES-611

---

RESTResource/reducer.js

Reverts #102 
Finishes cleaning up what was removed by https://github.com/folio-org/stripes-core/pull/735 in order to fix [STCOR-392](https://issues.folio.org/browse/STCOR-392).

Revert "Added PRUNE Redux action"

---

connect.js

follow up to #147 to keep lint quiet about keeping react quiet 🙄

be quiet react AND lint. sheesh

---

RESTResource/reducer.js
connect.js

Reverts folio-org/stripes-connect#113
I haven't investigated _how_ yet, but this PR is behind the "create user" screen getting stuck showing three blinking dots ad nauseum.
Refs [STCON-111](https://issues.folio.org/browse/STCON-111)

STCON-111 Revert "Init resource data correctly"

---

RESTResource/reducer.js
connect.js

This PR brings back the work done in #113 but with a fix to correctly initialize local resources based on the work done in https://issues.folio.org/browse/STCON-65 by @zburke

Bring back resource initialization

---

RESTResource/RESTResource.js

Do not refetch records if the current offset matches previously fetched offset.
https://issues.folio.org/browse/STCON-118

STCON-118: Do not refetch records if the current offset matches previously fetched offset

---

CHANGELOG.md
RESTResource/RESTResource.js
doc/api.md
test/RESTResource.js

Reverts folio-org/stripes-connect#174
#174 was in turn a revert of #173. This reverts to our broken state in order to cleanly apply a fix.

Revert "Revert "STCON-121: Allow 'headers' to be a function and interpreted""

---

CHANGELOG.md
epics/mutationEpics.js
epics/refreshEpic.js
package.json

https://issues.folio.org/browse/STCON-124
There is a corresponding PR in stripes-core. https://github.com/folio-org/stripes-core/pull/986 
They will need to be merged together.

STCON-124 Upgrade RxJS to v6

---

CHANGELOG.md
package.json

- Also adding react-redux to devDeps

STCON-139 Move react-redux to peerDeps

---

package.json

In order to run transpilation process we actually need stripes-cli around:
https://issues.folio.org/browse/STCON-140

STCON-140: Add stripes-cli as a dev dep

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml

The transpilation started causing issues in various places. This PR turns it off for now.

STCON-140: Turn off transpilation

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
.gitignore
CHANGELOG.md
doc/api.md
package.json

Reverts folio-org/stripes-connect#215

Revert "do not publish 'artifacts' to npm"

---

.github/CODEOWNERS

Refs [STCLI-166](https://folio-org.atlassian.net/browse/STCLI-166)

STCLI-166 implement CODEOWNERS

---

package.json

Remove engines and resolutions properties that are no longer necessary.
Refs [STCON-171](https://folio-org.atlassian.net/browse/STCON-171)

STCON-171 cleanup package.json
