CHANGELOG.md, OkapiResource.js, RESTResource.js, connect.js, epics/index.js, epics/mutations.js, epics/refresh.js, package.json
This PR introduces epics (side effects) in order to sync mutations with refresh. 
Here are couple details about the current setup:
* They refresh related resources after mutation happens
* The resources which will be refreshed have to be visible and match the path of the resource from where the mutation originates.
=> Introduce epics for side effects STCON-16

connect.js, package.json
Removes two warnings:
`Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see` https://fb.me/prop-types-docs
and 
`Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.`
=> Prop types deprecation warning

LocalResource.js, RESTResource/RESTResource.js
Not only more consistent, this should make all resources accessible from manifest functions so we can use them for things like client side joins.
=> Consistent store prefix for local resources STCON-36

epics/mutations.js
Since redux-crud is gone and we are following a new pattern for action names the mutations epic has to be adjusted.
=> Adjust mutations epic. Fixes STCOR-88

CHANGELOG.md, RESTResource/RESTResource.js, RESTResource/actionCreatorsFor.js, RESTResource/reducer.js, test/integration.js
If you set `accumulate: true` in your manifest, stripes-connect will offer
two additional actions on the (soon to be moved/renamed) props.mutator
object: `GET()` and `reset()`. It will also no longer automatically fetch
any records, instead, you trigger a fetch by calling GET and any records
returned are appended to the resource. It returns a promise that resolves to
an array of records. Optionally, you can specify a parameter in the same
format as the manifest options (eg. `{ path: 'users'   params: { query:
'water' } }`). reset() clears the resource.
=>  Initial work on "accumulate" manifest option with "GET" action STCON-33

connect.js, test/integration.js
This PR addresses the issue discovered in [STCON-40](https://issues.folio.org/browse/STCON-40). The biggest change is the place where the resources are being initialized (inside the `wrap` function). 
The side effect of this refactoring causes the `dataKey` to be present when the connection happens. Because of that a new param had to be introduced  to `connect` called `options` which can be used to pass a `dataKey`. 
What it means in practice is that instead of doing this:
```js
constructor(props) {
super();
this.connectedAbout = props.stripes.connect(About);
}
render() {
return (
<div>
<this.connectedAbout stripes={this.props.stripes} dataKey="1" />
<this.connectedAbout stripes={this.props.stripes} dataKey="2" />
</div>
);
}
```
we will need to do this:
```js
constructor(props) { …
```
=> Address reconnecting issues. Fixes STCON-40

RESTResource/RESTResource.js, connect.js
This is necessary for my trivial graphql demos as Apollo client defaults to props.data.
While I can't get the full integration suite running locally, this change doesn't make things worse near as I can tell---17 failures from CI npms, 4 failures linking stripes-connect with this change, 8 failures when I check out master on the linked stripes-connect and 8 failures again when I check this branch back out.
=> Remove last vestiges of props.data 

epics/mutations.js
The mutations epic was executing refresh for all currently registered resources. This PR fixes it by filtering the stream and taking only the resource which was actually mutated.
=> Fix mutations epic. Fixes STCON-46

CHANGELOG.md, RESTResource/RESTResource.js
Uses new logging category `mock`.
(Requires an additional argument to `mockProps`, a logger object. These function signatures are getting big, suggesting that more stuff should go into the resouce objects, accessible via `this`.)
I need this to have some hope of getting to the bottom of UIORG-38.
=> Add logging for mockProps

CHANGELOG.md, RESTResource/RESTResource.js
Allows `mockProps` to work properly with `dataKey` for the first time
with the new dataKey-at-connect-time convention.
Fixes STCON-50.
=> Pass `dataKey` into `substitute` so it can pass it through to `mockProps`

RESTResource/RESTResource.js
STCON-39: Added the ability to define the resourceShouldRefresh as a boolean or a function. The function should return a boolean. I have coded to maintain backward compatibility. If resourceShouldRefresh is not set it will default to prior functionality.
@MikeTaylor @mkuklis Please take a look and review.  Thanks Mark
I have tested code against UIU-248. I will also submit pull request for UIU-248(ui-users).
=> STCON-39 Added the ability to define the resourceShouldRefresh

RESTResource/RESTResource.js, connect.js
Resolves [STRIPES-480](https://issues.folio.org/browse/STRIPES-480)
Relates to PRs in
[ui-users](https://github.com/folio-org/ui-users/pull/253) and [stripes-components](https://github.com/folio-org/stripes-components/pull/251).
This exports the template compilation portion of the substitute function into a reusable exported function. It should be fully backwards compatible.
=> Exporting compilePathTemplate function

connect.js
Currently `dataKey` can only be passed in `options` object. With this PR, it can be set in the manifest per resource.
=> Allow dataKey in manifest

doc/api.md
That code's been deprecated so we shouldn't document it!
=> Remove @errorHandler section from API docs

RESTResource/RESTResource.js
This is part of the fixes to [UIU-466.](https://issues.folio.org/browse/UIU-466)
The underlying bug has probably been happening for a while, ever since the ability to abort requests from inside `makeQueryFunction` was added. Basically, you'd do something like the following: 
- Open Users, toggle the Active filter to checked. We fetch the list of users and set the `lastUrl` and cache the response.
- Toggle the Active filter to unchecked. We do not fetch the list of users because we require a query or filters, but do update the lastUrl.
- Open Settings, a module which doesn't fetch anything immediately anymore.
- Switch back to Users. We're probably in an unstable state now. If we aren't, toggle back to Settings and then back to Users again. We attempt to fetch, notice it's the same as …
=> RESTResource: Prevent trying to use cached response from aborted requests

CHANGELOG.md, RESTResource/RESTResource.js, RESTResource/actionCreatorsFor.js, doc/api.md, package.json
This is the functionality to turn off the `alert()`ing on failed mutations. Components opt into it currently but it'd be easy enough to flip around in the future. 
This is all just passing along that `throwErrors` prop, it's actually _used_ in an upcoming stripes-core pull.
=> STCON-67: Added `throwErrors` prop to resources

CHANGELOG.md, doc/api.md
Details about how to use `props.stripes.connect` and how/why to use the
`dataKey` option were completely absent.
Fixes [STCON-61](https://issues.folio.org/browse/STCON-61)
=> augment details for `connect`

CHANGELOG.md, RESTResource/RESTResource.js, connect.js, doc/api.md, package.json, test/integration.js
https://issues.folio.org/browse/STCON-68
This PR introduces a new `permissionsRequired` prop to a manifest's object. The initial discussion can be found here:
https://github.com/folio-org/ui-users/commit/8558adef98e1d135314eaf9831d2decc459021b0#diff-6c4a67641cbff8412246381fb1851b26
=> Add a new permissionsRequired option to a manifest's object. Fixes STCON-68

CHANGELOG.md, doc/api.md, epics/refresh.js
This PR introduces a new optional function called `shouldRefresh` to a manifest's object. If the function is present it will be used by the refresh epic to indicate if the give resource should be refreshed or not. 
The functionality is backwards compatible meaning that if the `shouldRefresh` is not present the path matching will be used instead.
=> Add shouldRefresh function to a manifest's object. Part of STCON-71

RESTResource/RESTResource.js
`this.mutationError` isn't defined. 
The options are to call `this.mutationHTTPError` or the `mutationError` exported from `actionCreatorsFor.js`. The latter is more appropriate based on what info we have at the caller site.
=> RESTResource: Call correct mutationError()

CHANGELOG.md, package.json
Part of resolution for https://issues.folio.org/browse/FOLIO-1707
`stripes-connect` and `stripes-form` will need major version bumps to prevent newer versions of `stripes-*` dependencies from leaking in.
=> Revert stripes-core v3.0.0 dependency change

CHANGELOG.md, package.json
Caret dependencies are too loose in the context of releasing a platform
and allow new minor release to "leak" up into a platform where the
differing versions can cause duplication errors.
Refs [STRIPES-608](https://issues.folio.org/browse/STRIPES-608)
=> make stripes-core dep more strict

package.json
The version on master must always be >= that of the version on a branch.
Otherwise, repos that update to a patch release (from a branch) may be
prevent from using the tip-of-master version provided in their
workspace.
=> sync master version with releases from branches

CHANGELOG.md, ConnectContext.js, connect.js, package.json, test/integration.js
Hot on the heels of  #79 , This PR involves bringing the 'rootContext' over to the `stripes-connect` side of the line.
- No breaking changes (if merged in close proximity to the stripes-core PR)
- Local HOC's/Contexts get needed for tests for either case.
- There can now be only one `stripes-connect` in the platform, due to the use of new Context API.
=> STCON-76  Option#2: core circular dependency withConnect

CHANGELOG.md, package.json
- Tested with sample "Hello World" UI app. No difference in bundle size but this will shake future unused code blocks.
=> Turned off sideEffects to enable tree-shaking

CHANGELOG.md, RESTResource/RESTResource.js, package.json
It's now possible for the `clientGeneratePk` manifest option to take any of the forms that `path` and other options can take. So for example, your manifest can specify `clientGeneratePk: '!{foo}'` to use the value of the `foo` prop. (This is in fact exactly what `<ControlledVocab>` does to allow its caller to pass in a prop indicating whether ot not to have the client generate an ID.
As well as adding the line that runs substitute on `clientGeneratePk`, I had to tweak `substitute` so it passes through boolean values (as the default value is `true`). While I was there, I made the diagnostic for an unsupported type a bit more verbose, as that would have helped me to track down what was otherwise a slightly obscure error thrown by the test suite.
=> Support substitution for clientGeneratePk

RESTResource/RESTResource.js, RESTResource/actionCreatorsFor.js, epics/mutationEpics.js, epics/refreshEpic.js, package.json
This PR is an attempt to fix issues described in https://issues.folio.org/browse/STCON-48, https://issues.folio.org/browse/STCON-49 and https://issues.folio.org/browse/STCON-80 
Instead of relying on the path template we can actually use the processed path (passed as a metadata).
The change proposed here should be backwards compatible with the previous implementation.
=> Improve mutation and refresh epics. Part of STCON-80

RESTResource/RESTResource.js
An undefined param was crashing Stripes when the `NotesSmartAccordion` was attempting to fetch notes. Debugged it to this line where it'd try to assign to a `null` value that was being returned from `this.verbOptions()`.
=> Prevent crash when verbOptions returns null

CHANGELOG.md, RESTResource/RESTResource.js, doc/api.md, package.json
This allows `getSASparams` to pass the props into a `queryGetter` function, so that the application can consult the props dynamically to determine how to massage the query within a static manifest.
=> Pass props into params function

CHANGELOG.md, LocalResource.js, RESTResource/RESTResource.js, connect.js, test/integration.js
The refresh was not handled for resources with paths defined as `!{prop}`. This PR should address it.
https://issues.folio.org/browse/STCON-81
=> Refresh resource with interpolated property when the prop changes. Fixes STCON-81.

RESTResource/RESTResource.js
- Matches the function signature of `params`
- Lets us avoid having to make assumptions like that the resource names in the third parameter will be `snake_cased`.
=> Pass props to `path` functions

RESTResource/RESTResource.js
Resources don't get refreshed when query params change. This fixes that.
=> RESTResource: Refresh when params change

RESTResource/RESTResource.js, connect.js
It looks like redux-form is causing an update of the connected parent components every time we type of focus on given for elements.
This PR is trying to limit the number of times we check if the resources should be refreshed by first checking if the props actually differ.
=> An attempt to improve form performance. Part of FOLIO-2158

RESTResource/RESTResource.js
This PR includes couple more performance improvements mentioned on Slack by @MikeTaylor and @zburke. 
It basically checks if the given resource has a property namespace `!{syntax}` defined as a path or if path or params are defined as functions. In other cases the refresh will be skipped.
=> Add couple more performance improvements. Part of FOLIO-2158

RESTResource/reducer.js
This is to address https://issues.folio.org/browse/UIIN-687 where performance slowly degrades over long periods of time. 
The approach here is to reset stored records when moving between modules since they do take up space in memory and can grow unbounded as you visit more modules and run additional searches. By calling PRUNE whenever switching modules, we ensure that at most only 1 set of records is stored in Redux at any given time, thus making memory usage more reasonable and more predictable. 
We will still be retaining search queries and other light pieces of metadata in Redux, so when moving back to a previously accessed module, the search is quickly re-run adding only a slight pause in user experience.
=> Added PRUNE Redux action

RESTResource/RESTResource.js
When using the `fetch` property on a resource, the resource may never get fetched.
For example, here's a manifest:
```
static manifest = Object.freeze({
logs: {
type: 'okapi',
path: 'erm/jobs/!{job.id}/!{type}Log',
fetch: props => props.fetch,
},
});
```
I want to lazy-load this endpoint. Ie, only fetch this endpoint when an accordion is open because the fetch is very expensive. So initially, the `fetch` prop I pass in is `false`, and when the accordion opens, it becomes `true`. However, because the `path` or `params` haven't changed, `shouldRefresh` returns `false`. As a result, this endpoint is never fetched.
I don't like the idea of ballooning this function, but:
- Most containers don't use functional `fetch`, so this check should be quite fast on average.
- The workaround is to do …
=> RESTResource: shouldRefresh when `fetch` goes true

CHANGELOG.md, connect.js
https://issues.folio.org/browse/STRIPES-659
We need a way to clear registered epics during the BigTest app `teardown` process:
https://github.com/folio-org/stripes-core/blob/master/test/bigtest/helpers/setup-application.js#L68
This is required because every time a new instance of the `App` is created we also initialize epics (a new instance of BehaviorSubject is created):
https://github.com/folio-org/stripes-core/blob/master/src/App.js#L32
https://github.com/folio-org/stripes-core/blob/master/src/configureEpics.js#L12
When this happens  the previously registered epics become stale. 
This PR exposes a new function via `connect` called `reset` which can be used in the BigTest `teardown` hook to clear the epics.
=> Add ability to clear registered epics. Part of STRIPES-659

RESTResource/RESTResource.js
this causes issues in tests for ui-finance: https://jenkins-aws.indexdata.com/job/folio-org/job/ui-finance/job/PR-166/6/console
If you look into `this.verbOptions()` you'll find that result might be `null`. So it's better to check this.
=> avoid Error: Uncaught TypeError: Cannot read property 'fetch' of null

CHANGELOG.md, RESTResource/RESTResource.js, connect.js
This PR is an idea from @zburke based on the issue found in https://github.com/folio-org/ui-circulation/pull/474
There are some cases where remounted connected components render stale data. In most cases that's fine but when the  `resourceShouldRefresh` is present the expectation is to receive a fresh data when the component is remounted / reconnected.
=> Introduce a way to reset resources with resourceShouldRefresh present when component unmounts. Refs UICIRC-365.

CHANGELOG.md, RESTResource/RESTResource.js
When paging ends unexpectedly because Okapi goes from returning
`totalRecords=999999999` to e.g. `totalRecords=100`, an extra request
will be triggered that will receive `totalRecords=0`. When this happens,
we need still need to trigger a PAGE_SUCCESS event to indicate that
paging has ended, but we need to do so _without_ resetting the final
record count to 0.
Yeah, it's a bit messy. Additional details in the comments.
Refs [STSMACOM-259](https://issues.folio.org/browse/STSMACOM-259), [STCON-90](https://issues.folio.org/browse/STCON-90)
=> STCON-90 gracefully handle paging requests based on bad totalRecords estimates

CHANGELOG.md, RESTResource/RESTResource.js, package.json
PO reports of results list populating with unrequested results when only one result was present before - this would happen when clicking through to details or returning from an edit view (ui-users).
This can be  reproduced if you check a filter, get results, and then enter a search string in `ui-users` and click search (reducing the results list to one.) Once you click on the details page, the result list will fill up again (as if produced by the filter alone.)
This was the result of cached paging data still left in the redux store.
The paged cache would be passed on as a fetch success when a connected component was re-instantiated due to https://github.com/folio-org/stripes-connect/blob/master/connect.js#L91
I don't know if this is the solid solution - but it wouldn't surprise me if this …
=> UIU-1405 - results list ghost data

CHANGELOG.md, RESTResource/RESTResource.js
PO reports of results list populating with unrequested results when only one result was present before - this would happen when clicking through to details or returning from an edit view (ui-users).
This can be  reproduced if you check a filter, get results, and then enter a search string in `ui-users` and click search (reducing the results list to one.) Once you click on the details page, the result list will fill up again (as if produced by the filter alone.)
This was the result of cached paging data still left in the redux store.
The paged cache would be passed on as a fetch success when a connected component was re-instantiated due to https://github.com/folio-org/stripes-connect/blob/master/connect.js#L91
I don't know if this is the solid solution - but it wouldn't surprise me if this …
=> STCON-91 reset paging cache on successful fetch

CHANGELOG.md, MIGRATIONPATHS.md, README.md, RESTResource/RESTResource.js, RESTResource/actionCreatorsFor.js, RESTResource/reducer.js, package.json, test/integration.js, test/reducer.js
- Fulfills [STCON-57](https://issues.folio.org/browse/STCON-57).
- Created an opt-in path for requesting pages one-at-time by offset.
- Created MIGRATIONPATHS.md to document opt-in instructions for module developers.
- Tested opt-in against ui-inventory.
- Ran against modules that have not yet opted-in to ensure backwards compatibility.
=> Add support for requesting pages individually by offset

CHANGELOG.md, RESTResource/RESTResource.js
Some backends respond with the updated record when returning from a PUT endpoint. This is especially useful when the backend doesn't persist the record as-is, but adds/removes some properties such as nested ids.
In those scenarios, the only way to get the canonical record is to either:
1. Do ugly `componentDidUpdate` (or similar) checks for if the component's `resources` changed.
1. Manually chain on a call to the GET mutator.
Both of these patterns are discouraged in general, so this provides a saner option where the backend's response is returned from the PUT if it's JSON.
If the backend's response _is not_ JSON, then the behaviour doesn't change; we continue to respond with the `clientRecord` that was sent to the backend.
=> STCON-92: PUT mutator returns server response if avail

MIGRATIONPATHS.md, doc/api.md
I was hoping to put a warning into the code so that we could log a `console.warning`, but it doesn't seem possible because the `pagingType` is available only in `MCLRenderer` while the `resultOffset` is in stripes-connect. :\
I figure this gives the most visibility to the gotcha.
=> Added warnings in docs for resultOffset

RESTResource/RESTResource.js
This is a bug fix I introduced in https://github.com/folio-org/stripes-connect/pull/126
The `opts` param in `createAction` was passed in a wrong place.
Apologies for this @zburke. This is needed to correctly address 
https://issues.folio.org/browse/UIU-1299
=> UIU-1295: Fix opts param in create action

CHANGELOG.md, doc/api.md, epics/mutationEpics.js
This lets us better scope the `shouldRefresh` for our resources. 
For example, if we have a resource that we fetch/update/refresh, but also enable the deletion of, the delete will trigger a REFRESH action on that resource that will throw an error (likely a 404). We can sometimes solve this by passing `{ silent: true }`, but then other resources that _should_ refresh based on the deletion aren't refreshed.
Now we can write something like this:
```
shouldRefresh: (resource, action) => {
if (resource.name !== 'agreement') return true;
return !action.meta.originatingActionType?.includes('DELETE');
},
```
[Slack thread that started this was this one.](https://folio-project.slack.com/archives/C210UCHQ9/p1584993996003600)
=> Added originatingActionType to REFRESH action.meta

CHANGELOG.md, MIGRATIONPATHS.md, README.md, RESTResource/RESTResource.js, RESTResource/actionCreatorsFor.js, RESTResource/reducer.js, test/integration.js, test/reducer.js
Provide an opt-in path for requesting pages one-at-a-time by offset, i.e. by clicking a "Load more" button, as an alternative to infinite scroll. 
It's a cherry-pick of the commits in #117 onto a patch branch in order to make that feature, and that feature alone, available as a patch to the [2019-q4 stripes release](https://github.com/folio-org/stripes/releases/tag/v2.12.1).
=> STCON-57 support paged offset

CHANGELOG.md, RESTResource/RESTResource.js
Correctly receive `opts` in `createAction`.
Refs [UIU-1295](https://issues.folio.org/browse/UIU-1295)
=> UIU-1295 correctly receive opts in createAction

package.json
The master branch version must be >= the latest released version in
order for clones in a workspace to be accepted as fulfilling the current
stripes dep on `~5.5.1`.
=> bump package patch in concert with latest release

CHANGELOG.md, doc/api.md
These additions to the API documentation refelect my recent experiences in catching and reporting errors in the Course Reserves app, and should save some time for those who subsequently have to figure out the same stuff.
=> Expand documentation on error reporting

connect.js
Currently we just blaze ahead trying to index into Component. When the Component is undefined, this is a problem. Let's give better info about why a component may be undefined.
=> throw better errors

CHANGELOG.md, RESTResource/RESTResource.js
https://issues.folio.org/browse/STCON-102
It looks like we were using a wrong action for restarting pagination which caused part of the redux store to leak:
The easiest way to reproduce it is to go to ui-users and keep switching between users.
@ryandberger I'm not sure if the `[]` defined in:
https://github.com/folio-org/stripes-connect/blob/master/RESTResource/RESTResource.js#L362
is fine here (things seem to work as expected) or if we need to use the single entry defined in:
https://github.com/folio-org/stripes-connect/blob/master/RESTResource/RESTResource.js#L366-L371
BTW here is how things look like after this change:
=> STCON-102: Restart paging correctly

CHANGELOG.md, connect.js
`cWRP` is so noisy in the console, and we know we need to refactor. The
console noise isn't helping; it's just annoying.
Refs [STCON-70](https://issues.folio.org/browse/STCON-70)
=> STCON-70 shush, componentWillReceiveProps

RESTResource/reducer.js, connect.js
This PR initializes resource data with the correct structure which makes it available during the first render.
Instead of doing:
`get('resources', 'resourceName.records', [])`;
resources structure will be always present:
`resources.resourceName.records`
This change should be part of the next major release.
=> Init resource data correctly

CHANGELOG.md, RESTResource/RESTResource.js, RESTResource/actionCreatorsFor.js
Right now there is no possibility to override *throwErrors* option for a certain mutator which would be nice so an error is shown for all resource actions except the certain mutator for a which a custom solution implemented (e.g. callouts). In order to disable the error alert right now, *throwErrors* flag should be set for the whole resource, which is not good as it would be nice to show error alerts for other actions (e.g. *GET* requests) by default. The idea of the [STCON-112](https://issues.folio.org/browse/STCON-112) story is to provide the possibility to override resource *throwErrors* value for mutators: *POST*, *PUT*, *DELETE*.
```
mappingProfile: {
type: 'okapi',
path: 'data-export/mappingProfiles/:{id}',
PUT: { throwErrors: false },
}
```
=> STCON-112: Allow mutators to configure `throwErrors` option

OkapiResource.js, RESTResource/RESTResource.js, connect.js, doc/api.md, package.json, test/integration.js
This PR does 2 different things.
1. It will automatically cancel all pending requests (It will abort a promise) when the connected component unmounts.
2. It introduces a new method accessible via mutator called `cancel` (which can be used to manually cancel pending promises) to help in situations like the one in https://github.com/folio-org/ui-users/pull/1306/files where the child of the connected parent component unmounts.
https://issues.folio.org/browse/STCON-104
I started with `cancelable` promise as described here first:
https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html
but then discovered that some people complained about memory leakage with that approach under: https://github.com/facebook/react/issues/5465
Then based on the suggestion from @NikitaSedyx  in …
=> STCON-104: Add ability to cancel pending requests

CHANGELOG.md, RESTResource/RESTResource.js, package.json
Stripes-connect allows us to return a `null` value as a part of the `params` option. For eg: [here](https://github.com/folio-org/ui-agreements/blob/master/src/routes/AgreementEditRoute.js#L121). I believe the general understanding is that returning `null` from `params` means the `url` to be built is incomplete and hence is returned as `null` and the fetch is not triggered. But, currently adding the `perRequest` [option](https://github.com/folio-org/ui-agreements/blob/master/src/routes/AgreementEditRoute.js#L114) to the manifest by-passes this idea and triggers a fetch by adding a `limit` param to the url. 
Considering that the `params` options should be the single source of truth and returning `null` shouldn't trigger a fetch, this PR fixes that issue by adding an additional null check. …
=> STCON-115 Added additional check to see if params is null

CHANGELOG.md, package.json
Bumping the major version of a peer-dep requires bumping your own major
version too. Whoops.
Refs [STCON-119](https://issues.folio.org/browse/STCON-119)
=> STCON-119 bump major to v7

CHANGELOG.md, package.json
Reverts folio-org/stripes-connect#166 (major version bump) ... in prep for reverting #165 (increment to react v17), due to unforeseen problems with testing.
Crackerjack research by @aditya-matukumalli and @mkuklis suggests [onFocus changes in React 17](https://github.com/facebook/react/issues/19743), which have caused [event handling trouble for others](https://eng.wealthfront.com/2021/01/14/upgrading-to-react-17-how-to-fix-the-issues-and-breaking-changes/), may be causing [our woes](https://issues.folio.org/browse/STCOR-504) too. 
Refs [STRIPES-722](https://issues.folio.org/browse/STRIPES-722)
=> STRIPES-722 Revert "STCON-119 bump major to v7"

CHANGELOG.md, RESTResource/RESTResource.js, doc/api.md, test/RESTResource.js
It is conceivable that a request may contain headers that need value
substitution to take place (as per query parameters, path components
etc.). This commit adds that.
The ability for the 'headers' value to be a function as well as an
object, as per 'path' etc. This allows us to access props that have
been passed to the component.
The use case this was implemented for was to allow an external
API key, that was being passed down to a component as a prop, to be used
in an authentication header for an API call being made by the child
component.
=> STCON-121: Allow 'headers' to be a function and interpreted

CHANGELOG.md, RESTResource/RESTResource.js, doc/api.md, test/RESTResource.js
Reverts folio-org/stripes-connect#173
I'm not sure of the exact mechanism, but #173 is causing resources that used to return `null` not to, causing them to execute when they should not. For example, visiting ui-users causes the query 
```
/users?limit=100&query
```
to run automatically, even though the `query` attribute is empty. This results in a 400 response from Okapi which the UI relays in a JS alert: 
```
ERROR: in module @folio/users, operation GET on resource 'records' failed, saying: org.folio.cql2pgjson.exception.QueryValidationException: 
org.z3950.zing.cql.CQLParseException: expected index or term, got EOF
```
because it expected a URL like 
```
/users?limit=100&query=some-value
```
but the emptiness of `value` is what should have prevented the query from running in the first …
=> Revert "STCON-121: Allow 'headers' to be a function and interpreted"

CHANGELOG.md, OkapiResource.js
Provide the tenant's locale setting in the HTTP `Accept-Language` header
to `OkapiResource` requests. This is the standard way for an HTTP client
to indicate the languages it understands.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
Refs [STCON-127](https://issues.folio.org/browse/STCON-127), [STRIPES-750](https://issues.folio.org/browse/STRIPES-750)
=> STCON-127 provide Accept-Language header to OkapiResource requests

RESTResource/RESTResource.js, RESTResource/actionCreatorsFor.js, RESTResource/reducer.js, babel-test-hook.js, constants.js, test/integration.js
https://issues.folio.org/browse/STCON-123
This PR is a continuation of the work @JohnC-80 and @ryandberger did under https://github.com/folio-org/stripes-connect/tree/sparse-array-option. 
It introduces a new manifest option called `resultDensity` which defaults to `dense`. In order to opt-in for pagination the `resultDensity` can be set to `sparse`.
=> STCON-123: Introduce result density option for pagination component 

.eslintrc, CHANGELOG.md, RESTResource/RESTResource.js, RESTResource/reducer.js, babel-test-hook.js, package.json
Use current `eslint-parser`, `eslint`, `fetch-mock`, `jsdom`, `uuid`. I
just couldn't handle the build warnings any more. Of course now that
`eslint-config-stripes` relies on `stripes-webpack` for its config,
there are actually _more_ build warnings from that, Alas.
Refs [STCON-130](https://issues.folio.org/browse/STCON-130)
=> STCON-130 update many outdated dependencies

CHANGELOG.md, connect.js, hooks/index.js, hooks/useComponentWillMount.js, hooks/usePrevious.js
stripes-connect uses class based component with lifecycle methods which are deprecated and will be removed in react 18. 
We should try to refactor it to use a functional component.
https://issues.folio.org/browse/STCON-132
=> STCON-132: Refactor connect to use a functional component

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json
Bump to NodeJS 16, Active LTS.
Refs [STCON-134](https://issues.folio.org/browse/STCON-134)
=> STCON-134 bump NodeJS to v16 in CI

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, package.json
https://issues.folio.org/browse/STCON-140
npm was not executing `prepublish`. This PR adds a step to do it explicitly in CI.
=> STCON-140: Enable transpilation on CI

CHANGELOG.md, index.js, package.json
Use `index.js` to correctly export public API.
https://issues.folio.org/browse/STCON-144
=> STCON-144: Use index.js to correctly export public API

.gitignore, CHANGELOG.md, package.json
Update the deps that can be updated painlessly. Those that remain are tricker:
* `query-string` has migrated to ESM only, which is great, except that it'll break the rest of the platform so until everybody migrates to jest-config-stripes where we can add a universal exception, we're not going to touch it here.
* `enzyme` and related things are woefully ancient but removing them would require a wholesale rewrite of the tests here. That may be worthwhile, but it's not gonna happen in the scope of this ticket.
Refs [STCON-145](https://issues.folio.org/browse/STCON-145)
=> STCON-145 update deps

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, package.json
Short version of a long story: transpilation by itself offers no benefit, and transpiling and bundling (which is what the `stripes-cli transpile` command actually does at present) is not the appropriate at this level (only the leaf node of a JS app should be bundled; for us, that's the platform).
Refs [STCON-140](https://issues.folio.org/browse/STCON-140)
=> STCON-140 do not transpile

CHANGELOG.md, package.json
Align the semver constraint on redux with other portions of the platform (namely stripes and platform-complete) in order to guarantee a singleton and to facilitate the eventual move of this dependency to peer.
Refs [STCON-146](https://issues.folio.org/browse/STCON-146), [STRIPES-860](https://issues.folio.org/browse/STRIPES-860)
=> STCON-146 align redux semver with in-use version

CHANGELOG.md, package.json
Transpile (STCON-140, PR #207) was partially reverted in PR #211 but I neglected to correctly revert `package.json`, which is now fixed here.
Refs [STCON-140](https://issues.folio.org/browse/STCON-140)
=> STCON-140 finish transpile revert

CHANGELOG.md, OkapiResource.js, doc/api.md, test/OkapiResource.js
purpose: in scope of consortia work we need to fetch resources from different tenants, but there are some legacy class components that use manifests and stripes-connect. There is an option to override to hooks approach, but there are cases when it's required to override whole plugin (ui-plugin-find-user)
approach: introduce new optional okapi resource property to define tenant to be passed in headers. Usage can be reviewed in related PR
related to https://github.com/folio-org/ui-plugin-find-user/pull/238
=> STCON-150 Support tenant override in okapi resources

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
In CI, bump NodeJS from v16 to v18.
Refs [STCON-149](https://issues.folio.org/browse/STCON-149)
=> STCON-149 use NodeJS v18 in CI

CHANGELOG.md, OkapiResource.js, RESTResource/RESTResource.js
Handle access-control via cookies by way of the `Credentials: include` HTTP request option.
Refs [STCON-138](https://issues.folio.org/browse/STCON-138), [FOLIO-3627](https://issues.folio.org/browse/FOLIO-3627)
=> STCON-138 handle access-control via cookies

CHANGELOG.md, OkapiResource.js
Include `application/json` in the `Accept` header for `PUT` and `DELETE` responses in Okapi requests. This change does not represent a change in policy but rather brings the code into compliance with reality, where API requests may fail and provide JSON error messages. In fact, existing code already supports this (e.g. we inspect the content-type in `PUT` responses, which would be unnecessary if this convention were strictly followed). Many APIs likely do this, but we just didn't notice because they do not conduct content-type negotiations. New APIs with more strictly-compliant tooling do, however, and this default will allow UI code to use them without needing to override the too-strict default values.
Putting good defaults in one place feels better than permitting a strict default to be …
=> STCON-154 provide more lenient Accept values for PUT, DELETE

.github/workflows/ui.yml
There is no module descriptor here. Additionally, make this workflow
conditional to avoid running twice when GA logs multiple events for the
same action when opening a new PR.
Refs [STCON-165](https://folio-org.atlassian.net/browse/STCON-165), [STRIPES-938](https://folio-org.atlassian.net/browse/STRIPES-938)
=> STCON-165 GA: omit publishing MD 
